[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/search"
  to = "/.netlify/functions/search"
  status = 200

[[redirects]]
  from = "/test-uspto"
  to = "/.netlify/functions/test-uspto"
  status = 200

[[redirects]]
  from = "/test-gemini"
  to = "/.netlify/functions/test-gemini"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
